server:
  port: 8001

spring:
  application:
    name: short-link-admin
  datasource:
#        url: jdbc:mysql://localhost:3306/link?useUnicode=true&characterEncoding=utf8
#        username: root
#        password: 123456
#        driver-class-name: com.mysql.cj.jdbc.Driver

    # ShardingSphere 对 Driver 自定义，实现分库分表等隐藏逻辑
        driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    # ShardingSphere 配置文件路径
        url: jdbc:shardingsphere:classpath:shardingsphere-config-${database.env:dev}.yaml
  # 定义 MVC 的模板
  mvc:
    view:
      prefix: /templates/
      suffix: .html

  data:
    redis:
      host: 127.0.0.1
      port: 6379